# Generated by Django 4.2.4 on 2023-08-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.TextField()),
                ('UserID', models.IntegerField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('email_id', models.EmailField(max_length=254)),
                ('password', models.TextField()),
            ],
        ),
    ]
