# Generated by Django 4.2.4 on 2023-08-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_userdetails_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Moviename', models.CharField(max_length=100)),
                ('MovieID', models.IntegerField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('Movietype', models.CharField(max_length=100)),
            ],
        ),
    ]
