# Generated by Django 4.2.4 on 2023-08-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_moviedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetails',
            name='Movietype',
            field=models.IntegerField(),
        ),
    ]
