# Generated by Django 4.2.4 on 2023-08-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_moviedetails_moviename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetails',
            name='MovieID',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='UserID',
            field=models.IntegerField(unique=True),
        ),
    ]
