# Generated by Django 4.2.4 on 2023-08-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_userdetails_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviedetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='moviedetails',
            name='MovieID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='moviedetails',
            name='Moviename',
            field=models.CharField(max_length=100),
        ),
    ]
