# Generated by Django 4.2.4 on 2023-08-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_moviedetails_movieprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieBooking',
            fields=[
                ('BookingID', models.IntegerField(primary_key=True, serialize=False)),
                ('MovieID', models.IntegerField()),
                ('Movieprice', models.IntegerField(default=100)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('Quantity', models.IntegerField(default=1)),
            ],
        ),
    ]
