# Generated by Django 4.2.4 on 2023-08-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_moviebooking_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviebooking',
            name='UserID',
            field=models.IntegerField(default=1),
        ),
    ]
