# Generated by Django 4.2.4 on 2023-08-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_userdetails_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='UserID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
