# Generated by Django 4.2.4 on 2023-08-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_Booking',
            fields=[
                ('BookingID', models.AutoField(primary_key=True, serialize=False)),
                ('MovieID', models.IntegerField()),
                ('Movieprice', models.PositiveIntegerField()),
                ('date_added', models.DateField(auto_now=True)),
                ('date_updated', models.DateField(auto_now_add=True)),
                ('Quantity', models.PositiveIntegerField()),
                ('UserID', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie_Details',
            fields=[
                ('MovieID', models.AutoField(primary_key=True, serialize=False)),
                ('Moviename', models.CharField(max_length=100)),
                ('date_added', models.DateField(auto_now=True)),
                ('date_updated', models.DateField(auto_now_add=True)),
                ('Movietype', models.CharField(max_length=100)),
                ('Movieprice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Details',
            fields=[
                ('UserID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=100)),
                ('date_added', models.DateField(auto_now=True)),
                ('date_updated', models.DateField(auto_now_add=True)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField()),
                ('phone', models.CharField(max_length=12, unique=True)),
            ],
        ),
    ]
