# Generated by Django 4.2.4 on 2023-08-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_movie_booking_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_booking',
            name='Movieprice',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='movie_booking',
            name='Quantity',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='movie_booking',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='movie_booking',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='movie_booking',
            name='deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='movie_details',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='movie_details',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='UserID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
