# Generated by Django 4.2.4 on 2023-08-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_alter_movie_booking_movieprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_booking',
            name='Movieprice',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='movie_booking',
            name='Quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
